version: '3'
services:
  ftp-server:
    image: stilliard/pure-ftpd
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: ftpUser
      FTP_USER_PASS: ftpPass
      FTP_USER_HOME: /home/ftpUser
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./out/run/ftpServerContent:/home/ftpUser/"
    restart: on-failure
  statements-loader:
    build:
      context: ./statements-loader
    image: luchoct/statements-loader
    depends_on:
      - statements-processor
    environment:
      LOGLEVEL: INFO
      FTP_SERVER: ftp-server
      FTP_USER: ftpUser
      FTP_PASSWORD: ftpPass
      FTP_PASSIVE: "False"
    volumes:
      - "./out/run/generatedFiles:/loader/out"
    restart: on-failure
  mongo-db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: bank-transfers
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminPass
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro"
#      - "./out/run/mongoData:/data/db"
    restart: on-failure
  statements-processor:
    build:
      context: ./statements-processor
    image: luchoct/statements-processor
    depends_on:
      - ftp-server
      - mongo-db
    environment:
      spring.data.mongodb.uri: mongodb://bankTransfersUser:bankTransfersPass@mongo-db:27017/bank-transfers
      ftpServer.host: ftp-server
      ftpServer.port: 21
      ftpServer.username: ftpUser
      ftpServer.password: ftpPass
      ftpServer.clientMode: 0
    restart: on-failure
