version: '3'
services:
  ftp-server-statements-loader-standalone:
    image: stilliard/pure-ftpd
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: ftpUser
      FTP_USER_PASS: ftpPass
      FTP_USER_HOME: /home/ftpUser
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./out/run/ftpServerContent:/home/ftpUser/"
    restart: on-failure
  statements_loader-standalone:
    tty: true
    build:
      context: .
    depends_on:
      - ftp-server-statements-loader-standalone
    environment:
      LOGLEVEL: DEBUG
      FTP_SERVER: "ftp-server-statements-loader-standalone"
      FTP_USER: ftpUser
      FTP_PASSWORD: ftpPass
    volumes:
      - "./out/run/generatedFiles:/loader/out"
    restart: on-failure
