version: '3'
services:
  ftp-server:
    image: stilliard/pure-ftpd
    environment:
      PUBLICHOST: "0.0.0.0"
      FTP_USER_NAME: ftpUser
      FTP_USER_PASS: ftpPass
      FTP_USER_HOME: /home/ftpUser
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./out/run/ftpServerContent:/home/ftpUser/"
    restart: on-failure
  statements-loader:
    build:
      context: .
    image: luchoct/statements-loader
    depends_on:
      - ftp-server
    environment:
      LOGLEVEL: INFO
      FTP_SERVER: ftp-server
      FTP_USER: ftpUser
      FTP_PASSWORD: ftpPass
      FTP_PASSIVE: "False"
    volumes:
      - "./out/run/generatedFiles:/loader/out"
    restart: on-failure
