spring:
  profiles:
    active: prod

logging:
  level:
    org.springframework: ERROR
    com.luchoct: DEBUG

# TODO remove
ftpServer:
  host: 0.0.0.0
  port: 21
  username: ftpUser
  password: ftpPass
  clientMode: 2

sourceFiles:
  charset: UTF-8

channel:
  statementsFileRead:
    localDirectory: out/run/temporaryFtpFiles

