spring:
  profiles:
    active: prod

# data.mongodb.uri to be set on launching the App.
# ftpServer properties (host, port, username, password and clientMode) to be set on launching the App.

logging:
  level:
    ROOT: WARN
    com.luchoct: INFO

sourceFiles:
  charset: UTF-8

channel:
  statementsFileRead:
    localDirectory: out/run/temporaryFtpFiles

